function calib = nacteni_txt(cesta)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: V:\4_mag\Lecture4_23\MED\Data\im1\calib.txt
%
% Auto-generated by MATLAB on 09-Mar-2023 10:41:47

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "=";

% Specify column names and types
opts.VariableNames = ["cam0", "VarName2"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["cam0", "VarName2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["cam0", "VarName2"], "EmptyFieldRule", "auto");

% Import the data
calib = readmatrix(cesta, opts);


%% Clear temporary variables
clear opts

